backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: /images/uploads
site_url: https://matootie.com
logo_url: https://matootie.com/images/logo.png
slug:
  encoding: ascii
  clean_accents: true
collections:
- label: Blog
  name: blog
  description: Posts for my blog.
  create: true
  folder: content/posts
  slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
  fields:
  - label: Title
    name: title
    widget: string
  - label: Body
    name: body
    widget: markdown
    modes:
    - rich_text
  - label: Date published
    name: published
    widget: datetime
    time_format: false
    picker_utc: true
  preview: false
  sortable_fields:
  - title
  - published