backend:
  name: git-gateway
  branch: main
media_folder: public/uploads
public_folder: uploads
site_url: https://matootie.com
display_url: matootie.com
logo_url: https://matootie.com/logo.png
locale: en_CA
show_preview_links: false
slug:
  encoding: ascii
  clean_accents: true
collections:
  - name: config
    label: Configuration
    files:
      - name: config
        label: Config
        file: content/config.yml
        extension: yml
        format: yml
        fields:
          - name: site
            label: Site name
            widget: string
            required: true
            hint: The name of the site.
          - name: twitter
            label: Twitter
            widget: string
            required: true
            hint: The Twitter account of the site. Please include the @ symbol.
    preview: false
  - name: pages
    label: Pages
    files:
      - name: home
        label: Home
        file: "content/pages/home.md"
        fields:
          - label: Metadata
            name: meta
            widget: object
            collapsed: true
            summary: "{{fields.title}}"
            fields:
              - label: Title
                name: title
                widget: string
                required: true
                hint: Title that appears in searches and shares. Should be between 50 and 70 characters.
              - label: Description
                name: description
                widget: string
                required: true
                hint: Description that appears in searches and shares. Should be between 40 and 160 characters.
              - label: Type
                name: type
                widget: select
                default: website
                options:
                  - website
                multiple: false
                required: true
                hint: The type of content that this particular page is a part of.
              - label: Canonical URL
                name: url
                widget: string
                required: true
                hint: Specify the absolute URL to this page to prevent duplicate content in indexes.
              - label: Image
                name: image
                widget: image
                required: false
                hint: Optional image to include and display when users share this link.
                allow_multiple: false
          - label: Title
            name: title
            widget: string
            required: true
            default: Hello, world!
            hint: The title of the home page.
    preview: false
  - name: posts
    label: Posts
    label_singular: Post
    description: Posts for the blog.
    create: true
    folder: content/posts
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
        modes:
          - rich_text
      - label: Date published
        name: published
        widget: datetime
        time_format: false
        picker_utc: true
      - label: Banner
        name: banner
        widget: image
        allow_multiple: false
      - label: Excerpt
        name: excerpt
        widget: text
        hint: Brief excerpt or description of the post used for SEO.
    preview: false
    sortable_fields:
      - title
      - published
