name: Deploy to production

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    tags:
      - v1.[0-9]+.[0-9]+

permissions:
  contents: read
  deployments: write

concurrency:
  group: ${{ github.workflow }}-production
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Pull environment
        run: |
          vercel pull \
            --yes \
            --environment=production \
            --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build
        run: |
          vercel build \
            --prod \
            --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy
        run: |
          vercel deploy \
            --prebuilt \
            --prod \
            --token=${{ secrets.VERCEL_TOKEN }}
